version: "3.8"

services:
  app:
    container_name: react
    image: mivdev/program-cloud-web
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
        - "8080:80"
    env_file:
      .env